Azure/acr

- docs/FAQ.md
This is due to a change from the server side that untagged manifests used to return `null` for `tags` field but now the return value is an empty array such as
```
[
{
"digest": "sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a",
"tags": [],
"timestamp": "2019-01-09T03:21:58.3968339Z"
}
]
```
> Fix untagged manifest query

- docs/artifact-media-types.json
Adding `.chart.` to the config media type for Helm charts, as Helm client may want to specify more package types in the future (plugins etc.)
cc @sajayantony @SteveLasker
> Modify helm chart config media type

- docs/artifact-media-types.json
I've switched the media type for helm (again, sorry) based on the discussion here: https://github.com/helm/helm/pull/5719
I've also switched the description from "Helm artifacts" to "Helm charts" - given that Helm may choose to store things such as plugins as well in the future (which would also qualify as an artifact but have a separate media type)
> Modify Helm chart media type

- docs/artifact-media-types.json
Open Policy Agent bundles consist of a set of rego policy files,
JSON or YAML formatted data and an optional JSON formatted manifest
file with metadata about the bundle. This media type allows us to
support distributing OPA bundles as OCI images as well as simple tar files.
For the discussion of this in more detail see https://github.com/open-policy-agent/opa/issues/1413
> Add support for storing Open Policy Agent bundles as OCI artifacts

- README.md
Updating "Health Check CLI URL" from https://aka.ms/acr//health-check to https://aka.ms/acr/health-check
@sajayantony
> Health Check URL typo fixed

- README.md
i wonder if we should separate core links from conceptual doc links. Overtime if we put all conceptual doc links in the links table then the more common links might be harder to find.
> Add https://aka.ms/acr/import - acr import how-to-guide.

- docs/AAD-OAuth.md
Note, other script snippets already do this, and looks like we just missed this one
> disable line wrapping of base64 to maintain valid credential

- docs/Token-BasicAuth.md
GitHub Issue: https://github.com/Azure/acr/issues/291
Encoding base64 string in powershell/terminal instead of using the URL https://www.base64encode.org/
> Base64 encoding using powershell or terminal

- docs/image-transfer/ExportPipelines/azuredeploy.json
- docs/image-transfer/ExportPipelines/azuredeploy.parameters.json
- docs/image-transfer/ImportPipelines/azuredeploy.json
- docs/image-transfer/ImportPipelines/azuredeploy.parameters.json
We support either a system-assigned identity or a user-assigned identity for each ExportPipeline and ImportPipeline. The pipeline resources need to use the identity to access users' key vault to get the storage sas token secret.
The change adds the pipeline resource's identity to the key vault access policy in the same template.
To extract the principal ID of the system or user assigned identity of the deployed pipeline resource, we leverage the "reference' template function: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#reference
Key vault also exposes access policy as a resource "Microsoft.KeyVault/vaults/accessPolicies" so that we can add via the template: https://github.com/Azure/azure-quickstart-templates/blob/master/101-keyvault-a …
> Add KV secret access policy in the deployment of ExportPipeline and ImportPipeline

- docs/image-transfer/ExportPipelines/azuredeploy.json
- docs/image-transfer/ImportPipelines/azuredeploy.json
- docs/image-transfer/PipelineRun/azuredeploy.json
Options parameter is not required, so support a default value of empty array.
Fix the default value of artifacts to be an empty array. This parameter is not required to manually run an import pipeline.
> Add default values to pipeline templates

- samples/dotnetcore/image-transfer/ContainerRegistryTransfer/Helpers/IdentityHelper.cs
When creating a user identity dictionary entry, we cannot use null value or ARM will throw an exception
> Create user assigned identity entry with non-null value

- samples/dotnetcore/registry-artifact-transfer/README.md
- samples/dotnetcore/registry-artifact-transfer/src/Configurations/AzureEnvironmentConfiguration.cs
- samples/dotnetcore/registry-artifact-transfer/src/Configurations/ExportConfiguration.cs
- samples/dotnetcore/registry-artifact-transfer/src/Configurations/IdentityConfiguration.cs
- samples/dotnetcore/registry-artifact-transfer/src/Configurations/ImportConfiguration.cs
- samples/dotnetcore/registry-artifact-transfer/src/Configurations/RegistryConfiguration.cs
- samples/dotnetcore/registry-artifact-transfer/src/Configurations/SourceRegistryConfiguration.cs
- samples/dotnetcore/registry-artifact-transfer/src/Configurations/TransferDefinition.cs
- samples/dotnetcore/registry-artifact-transfer/src/Program.cs
- samples/dotnetcore/registry-artifact-transfer/src/Registry.cs
- samples/dotnetcore/registry-artifact-transfer/src/RegistryArtifactTransfer.csproj
- samples/dotnetcore/registry-artifact-transfer/src/RepositoryProvider/CatalogApiResponse.cs
- samples/dotnetcore/registry-artifact-transfer/src/RepositoryProvider/HttpMessageExtensions.cs
- samples/dotnetcore/registry-artifact-transfer/src/RepositoryProvider/RepositoryProviderV2.cs
- samples/dotnetcore/registry-artifact-transfer/src/RepositoryProvider/TagListApiResponse.cs
- samples/dotnetcore/registry-artifact-transfer/src/ResourceId.cs
- samples/dotnetcore/registry-artifact-transfer/src/TaskExtensions.cs
- samples/dotnetcore/registry-artifact-transfer/src/Transfer/ArtifactProvider.cs
- samples/dotnetcore/registry-artifact-transfer/src/Transfer/BlobCopier.cs
- samples/dotnetcore/registry-artifact-transfer/src/Transfer/ExportJob.cs
- samples/dotnetcore/registry-artifact-transfer/src/Transfer/ExportWorker.cs
- samples/dotnetcore/registry-artifact-transfer/src/Transfer/ImportJob.cs
- samples/dotnetcore/registry-artifact-transfer/src/Transfer/ImportWorker.cs
- samples/dotnetcore/registry-artifact-transfer/src/Transfer/TransferClient.cs
- samples/dotnetcore/registry-artifact-transfer/src/Transfer/TransferJobStatus.cs
- samples/dotnetcore/registry-artifact-transfer/src/TransferReport.cs
- samples/dotnetcore/registry-artifact-transfer/src/TransferResult.cs
- samples/dotnetcore/registry-artifact-transfer/src/transferdefinition.json
Publish Registry Artifact Transfer Tool as another sample for the ACR transfer feature. The tool supports streamline artifact transfer from one registry to another via both ACR image import and ACR transfer.
> Image transfer sample - Registry Artifact Transfer Tool

- docs/README.md
Remove dupe of ACR Links list, re-routing to the Links in the root README.md
> Remove dupe of ACR Links list

- docs/http-headers.md
This PR adds header values for the AKS Engine and Cluster API (capz) Kubernetes open source projects.
- AKS Engine: https://github.com/Azure/aks-engine
- capz: https://github.com/kubernetes-sigs/cluster-api-provider-azure
Also modified the table heading to "Service or Orchestrator name" to clarify that not all header names listed are services (neither AKS Engine nor capz is an Azure service!)
> docs: add AKS Engine and capz header values

- docs/image-transfer/ImportPipelines/azuredeploy.json
Registry deployment in import pipeline causes unexpected behavior with regards to registry properties such as dataEndpointEnabled, adminUserEnabled, and anonymousPull. Deploying an import pipeline in the current state will revert all of these values to false even on currently existing registries. Removing the ACR reference from the template fixes the issue.
> Remove registry deployment from import pipeline

- docs/custom-domain/deprecated/docker-vm-deploy/azuredeploy.json
- docs/custom-domain/deprecated/docker-vm-deploy/deploy-nginx-docker.sh
Documentation have been moved in 'deprecated' folder and some links have been broken.
> Update URLs in custom domain deprecated documentation

- docs/image-transfer/ExportPipelines/azuredeploy.json
Remove container registry from export pipeline template to avoid scenarios where customers accidentally overwrite registry properties when deploying an export pipeline.
> Remove registry deployment from export pipeline

- docs/http-headers.md
Propose to allow hierarchy path for optionalservicename, eg, azure/acr/`connected-registry/instance-1`
> propose hierarchy path for optionalservicename

- docs/teleport/edit-teleport-attribute.sh
This adds a little script to enable/disable teleport on a particular repository provided the registry is already teleport enabled. This helps manage which 10 repos someone may want to have teleport enabled in
> Create enable/disable teleport command for each repository

- docs/preview/connected-registry/quickstart-connected-registry-cli.md
If the ACR data endpoint is not enabled before, the connected registry create request will fail. Fix this ordering in our docs.
> Ensure ACR data endpoint is enabled before creating connected registry

- docs/teleport/collecting-teleportd-logs-aks.md
This is meant to be the customer facing guide on how to get logs for telepord
> Added information on how to collect logs from AKS instance's of Teleportd

- docs/AAD-OAuth.md
Mark all cases using AAD refresh token deprecated. The customer should use AAD access token.
> deprecate AAD refresh token support

- docs/teleport/README.md
- docs/teleport/find-teleport-enabled-repositories.sh
- docs/teleport/teleport-repository-management.md
This PR adds documentation on current teleport repository management restrictions and flow along with a convenience script to manage repositories to document the current flow.
> Add informational teleport docs on current teleport repository management

- docs/preview/connected-registry/overview-connected-registry-access.md
Links to the `az acr token` and `az acr scope-map` CLI commands resulted in 404.
> FIX: broken links to az acr CLI commands

- docs/preview/connected-registry/connected-registry-error-codes.md
This doc provides potential solutions to error codes that users may encounter in the `statusDetails` property of the connected registry resource. We will attach an link to this doc in each error description to improve discoverability.
```json
"statusDetails": [
{
"code": "DISK_PERMISSION_DENIED",
"correlationId": "52a46395-c89b-49c7-8a2c-d54e8b1574b9",
"description": "Access to the path 'D:\\var\\acr\\data1\\dummy.txt' is denied. For more information on troubleshooting this error, please visit https://aka.ms/acr/connected-registry/error-codes.",
"timestamp": "2021-04-02T01:17:45.394512+00:00",
"type": "Disk"
}
```
> Add connected registry error code reference doc

- docs/preview/connected-registry/README.md
- docs/preview/connected-registry/quickstart-view-connected-registry-repos-and-tags.md
The quickstart shows how to invoke v2 APIs to query available repositories and tags in a connected registry. Documenting other registry API requests, such as GET manifests, is out of scope.
> Add quickstart for viewing repositories and tags in a connected registry

- docs/preview/connected-registry/README.md
- docs/preview/connected-registry/release-notes.md
Publish release notes for each connected registry runtime version. These release notes will help the ACR team be more transparent to our customers about changes made during each connected registry release.
Note: we did not release a `0.4.0` version.
> Publish release notes for connected registry runtime

- docs/preview/connected-registry/quickstart-deploy-connected-registry-kubernetes.md
The new chart includes a proxy configuration fix and updates the default connected registry image to the `0.9.0`.
> Upgrade connected registry chart version

- docs/custom-domain/README.md
Following the docs, you get an error when accessing the new custom domain name with the openssl generated certificate.
```
Get "https://container-registry.contoso.com/v2/": x509: certificate relies on legacy Common Name field, use SANs instead
```
Need to specify the SAN extension with DNS to overcome this:
1. [Source 1](https://frasertweedale.github.io/blog-redhat/posts/2017-07-11-cn-deprecation.html)
2. [Source 2](https://stackoverflow.com/questions/64814173/how-do-i-use-sans-with-openssl-instead-of-common-name)
3. [Source 3](https://forums.docker.com/t/installed-docker-version-20-10-8-unable-to-docker-pull-because-of-error-x509-certificate-relies-on-legacy-common-name-field/116326)
> Add SAN extension to open-ssl docs

- docs/preview/quarantine/readme.md
- add cli example to enable/disable quarantine
> add cli example to enable/disable quarantine

- README.md
- docs/blog/teleport.md
- docs/preview/artifact-streaming/README.md
- docs/teleport/README.md
- docs/teleport/aks-getting-started.md
- docs/teleport/aks-teleport-comparison.md
- docs/teleport/collecting-teleportd-logs-aks.md
- docs/teleport/teleport-repository-management.md
- Updated old Project Teleport docs with the artifact streaming link.
- Updated the main README.md to be consistent with messaging and updated links for artifact streaming
> Artifact streaming

- docs/custom-domain/README.md
Custom domain support tickets are often created without the necessary information needed by the DRI to complete the onboarding request. This PR reverts the changes made previously to remove the Contact Us section.
> docs(customdomain): add the support section back to eliminate confusion

- docs/AAD-OAuth.md
According to [this article](https://learn.microsoft.com/en-us/cli/azure/msal-based-azure-cli), fetching AAD access token from `~/.azure/accessToken.json` is deprecated. It can now be fetched from `~/.azure/msal_token_cache.json` or by running `az account get-access-token --subscription "<your_subscription_name>"`. The AAD-oauth doc needs to be updated accordingly.
> docs: update how to fetch aad access token

- docs/preview/continuous-patching/README.md
List Running Tasks doesn't have required argument `--type -t` in example.
```sh
az acr supply-chain workflow list -r <registryname> -g <resourcegroup> [–-run-status <failed || successful || running>]
```
The correct command should be:
```sh
az acr supply-chain workflow list -r <registryname> -g <resourcegroup> [–-run-status <failed || successful || running>] -t continuouspatchv1
```
> Continous Patching Preview Documentation

- docs/preview/continuous-patching/README.md
ACR Continuous Patching Docs (https://aka.ms/acr/patching) are currently using en dashes throughout the docs.
This causes commands using the en dashes to fail and leads to CLI arguments not being recognized.
> Update patching docs to use hyphen instead of en dash
