- README.md
> add articles link

- docs/Troubleshooting Guide .md
> TSG for image not found issue

- docs/Troubleshooting Guide.md
> Formatting correction

- docs/http-headers.md
Added the config.json sample for how/where to add the header value.
Added cloud entries
> Add config.json sample

- docs/http-headers.md
Minor fix to cloud header table + alpha sort table rows.
> Headers update

- docs/FAQ.md
Add simple documentation for using Notary in ACR.
> Add FAQ for Content Trust

- docs/FAQ.md
> Revert "Add FAQ for Content Trust"

- samples/java/build/.factorypath
- samples/java/build/README.md
- samples/java/build/pom.xml
- samples/java/build/src/main/java/com/microsoft/azure/management/containerregistry/samples/ManageBuild.java
> update build java sample with the latest sdk

- docs/FAQ.md
> update FAQ with delete manifests cli command

- docs/FAQ.md
> Fix typo for content trust role assignment

- .github/ISSUE_TEMPLATE.md
> Adds a GitHub issue template

- docs/Tasks/container-registry-ref-acr-tasks-yaml.md
- Remove some unsupported functionality from the docs
> Remove some unsupported functionality from the docs

- docs/image-signing.md
> Fix typo in "Image Signing"

- docs/Tasks/container-registry-tasks-overview.md
> Fixes a YAML typo

- docs/FAQ.md
Provides check method and resolution for docker pull failures while docker push succeeds.
> Add FAQ for docker pull failures

- docs/FAQ.md
Added docs for the ARM template issue with Geo replication create using Complete mode of deployment.
> FAQ for ARM template issue with Geo replication

- docs/acr-roadmap.md
Updates to the roadmap:
- Content Trust Released
- Image Promotion Released
- Sovereign Clouds in Preview
- Auto Purge moved to the top of the backlog
> Roadmap Updates

- docs/preview/quarantine/quarantine-details/example.json
- docs/preview/quarantine/quarantine-details/schema.json
Add the scanner name in the details schema
> Add scanner name in the quarantine details schema

- docs/virtual-network/container-registry-vnet.md
> Doc change for to gain access

- docs/FAQ.md
> Added toc to faq

- docs/virtual-network/container-registry-vnet.md
Removed some references that are no longer needed
> Doc updates for VNet

- docs/AAD-OAuth.md
> Added script for docker login with ACR_ACCESS_TOKEN

- docs/custom-domain/docker-vm-deploy/nginx.conf.template
> Increase from default 1MB to 1000GB

- docs/FAQ.md
Update FAQ for content trust. Ask customer to re-login for role refreshing.
> Update FAQ.md for Content Trust

- docs/FAQ.md
Add a FAQ item for how to include .git folder in `az acr build` command.
> FAQ: include .git folder in build command

- docs/preview/quarantine/readme.md
the URL in the doc is malformed. Fix it
> fix the missing slash in the url

- docs/FAQ.md
- docs/integration/CircleCI.md
- docs/integration/github-actions/Dockerfile
- docs/integration/github-actions/github-actions.md
- docs/integration/github-actions/main.workflow
Add a sample GitHub Actions workflow.
Add a CI/CD section in FAQ.
> Add GitHub Actions example

- README.md
> Adding Task Timer Cron expressions

- README.md
> Additional links for Scheduling and Health Checks

- README.md
> Add jobs link

- README.md
Add https://aka.ms/acr/support/create-ticket to table of feedback links.
> Add azure support ticket link.

- README.md
Updated aka.ms links for Audit Logs and repo permisssions.
> Updated aka.ms links for Audit Logs and repo permisssions.

- README.md
Updated aka.ms links for repo permissions and audit logs.
> Updated aka.ms links for repo permissions and audit logs

- .github/workflows/nodejs.yml
- pages/blog/teleport.md
- pages/deploy.sh
Install vuepress globally
Update nodejs.yml
Trim to node 10.x
> Creating a publish action for github pages with deploy keys

- docs/.vuepress/config.js
- docs/blog/teleport.md
> Minor cleanup

- docs/TaskRuns/quickdockerbuild/README.md
- docs/TaskRuns/quickdockerbuild/azuredeploy.json
- docs/TaskRuns/quickdockerbuild/azuredeploy.parameters.json
- docs/TaskRuns/quickdockerbuildwithidentity/README.md
- docs/TaskRuns/quickdockerbuildwithidentity/azuredeploy.json
- docs/TaskRuns/quickdockerbuildwithidentity/azuredeploy.parameters.json
- docs/TaskRuns/quickrun/README.md
- docs/TaskRuns/quickrun/azuredeploy.json
- docs/TaskRuns/quickrun/azuredeploy.parameters.json
- docs/TaskRuns/taskrun/README.md
- docs/TaskRuns/taskrun/azuredeploy.json
- docs/TaskRuns/taskrun/azuredeploy.parameters.json
Add TaskRun samples. Copied from https://github.com/huanwu/armtemplates/tree/master/taskrun.
> Add TaskRun ARM template sample files

- docs/tasks/run-as-deployment/README.md
> Fixed deployment folder links

- docs/tasks/run-as-deployment/README.md
- docs/tasks/run-as-deployment/quickdockerbuildusingidentitykeyvault/README.md
- docs/tasks/run-as-deployment/quickdockerbuildusingidentitykeyvault/azuredeploy.json
- docs/tasks/run-as-deployment/quickdockerbuildusingidentitykeyvault/azuredeploy.parameters.json
Add a taskrun sample that use identity and keyvault.
> Add run as deployment using identity/keyvault sample

- docs/preview/BYOK/template.json
Adding template.json file for BYOK.
> Adding template.json file for BYOK

- docs/preview/BYOK/README.md
Updated How to sign-up for a private preview?
> Updated Readme

- docs/preview/BYOK/README.md
Final edits to the doc. Added key rotation details.
> Updated Readme file.

- docs/preview/CMK/README.md
Added link to template.json.file
> Added link to template.json file

- docs/CMK/README.md
Please recommend if there is a better way to communicate the alias with spam prevention considered.
> cmk: use recommended wording to register the feature

- docs/roles-and-permissions.md
> Removed typo in roles-and-permissions.md

- README.md
Updated ReadMe for Azure Policies link
> Updated ReadMe for Azure Policies link

- README.md
Updated Readme for Private Link
> Updated Readme for Private Link

- docs/acr-roadmap.md
Signed-off-by: steve lasker <stevenlasker@hotmail.com>
> Roadmap updates for VNet support

- docs/image-transfer/PipelineRun/azuredeploy.json
@jaysterp @sajayantony - Point fix to JSON file to validate
> Update azuredeploy.json - PipelineRun

- docs/tasks/agentpool/README.md
Signed-off-by: Steve Lasker <stevelasker@hotmail.com>
> Task Agent Pool doc updates

- README.md
Adding agent pool and re-organizing as the list expands
Signed-off-by: Steve Lasker <stevelasker@hotmail.com>
> ACR Link updates

- docs/AAD-OAuth.md
> Add documentation for catalog and tag listing with pagination

- docs/AAD-OAuth.md
> Remove unnecessary `export` in the example scripts

- README.md
> Fixed rest doc links

- docs/tasks/agentpool/README.md
Add Isolated Tier to Agent Pool
> Add Isolated Tier to Agent Pool

- docs/tasks/agentpool/README.md
add several new regions for agent pool
> update agent pool preview regions

- notifications/README.md
- notifications/helm-repo-failure-20200918-.md
> Add ACR Advisories, including Helm Advisory

- notifications/helm-repo-failure-20200918-.md
> Fix chart.yaml reference with index.yaml

- notifications/helm-repo-failure-20200918-.md
Update to reflect Helm `index.yaml` fix in deployment
> Advisory update

- notifications/helm-repo-failure-20200918-.md
> Helm-Azure commercial complete

- notifications/helm-repo-failure-20200918-.md
> Helm advisory rollout complete

- README.md
Add https://aka.ms/acr/tasks/gated-import
> Add Gated Import Workflow

- docs/teleport/aks-getting-started.md
- docs/teleport/check-expansion.sh
> Teleport: fix table and debug

- docs/teleport/aks-getting-started.md
Teleport has started to support managed identity in latest AKS cluster
> Teleport: update doc to support managed identity

- docs/AAD-OAuth.md
update with the latest claim set and also fix the word to make this section understanable
CC @toddysm
> doc: update oauth token claim sets

- docs/preview/connected-registry/quickstart-deploy-connected-registry-iot-edge-cli.md
Document the steps on how to deploy api proxy. Update connected registry and iotedge module versions to the latest ones.
> Document the steps on how to deploy api proxy module for connected registry. 

- README.md
> Add az link

- docs/preview/connected-registry/quickstart-deploy-connected-registry-kubernetes.md
The tutorial covers deployment of the connected registry using helm chart. Both HTTPS and HTTP scenarios are documented.
> Quickstart for connected registry deployment on Kubernetes

- docs/preview/connected-registry/release-notes.md
Add release notes for connected registry 0.8.0 release
> Add release notes for 0.8.0

- samples/dotnetcore/task/ManageTask/AzureUtility.cs
- samples/dotnetcore/task/ManageTask/ManageTask.csproj
- samples/dotnetcore/task/ManageTask/Program.cs
- samples/dotnetcore/task/README.md
- samples/dotnetcore/task/WeatherService/Dockerfile
- samples/dotnetcore/task/WeatherService/WeatherService.csproj
- samples/dotnetcore/task/WeatherService/acb.yaml
- upgrade sdk to dotnet 6
- upgrade to Azure.ResourceManager.ContainerRegistry
> feat: update task example

- docs/preview/connected-registry/release-notes.md
- update connected registry 0.9.0 release note
> doc: update connected registry 0.9.0 release note

- docs/preview/connected-registry/quickstart-deploy-connected-registry-iot-edge-cli.md
- docs/preview/connected-registry/quickstart-deploy-connected-registry-nested-iot-edge-cli.md
Update the dummy password areas to asterisks.
> [Connected Registry Doc] Update dummy password to asterisks

- README.md
Updated the artifact streaming hyperlink with the correct one
> Fix artifact streaming link

- docs/blog/abac-repo-permissions.md
- docs/preview/abac-repo-permissions/README.md
Fix ABAC Private Preview docs feature name and onboarding email
> Fix ABAC Private Preview Feature Name and Onboarding Email

- docs/preview/connected-registry/quickstart-deploy-connected-registry-kubernetes-v2.md
add a new doc about the updated instructions for connected registry helm deployment
> add updated instructions for connected registry helm deployment

- docs/AAD-OAuth.md
add guidance on obtaining an ACR audience AAD token
> doc: add guidance on obtaining an ACR audience AAD token

- docs/preview/continuous-patching/README.md
Changing extension and adding in a prereq calling out Free Subscriptions
> Updating documentation with new wheel file and restrictions

- README.md
Added the correct link to the READMe per guidance.
> Updated acr links for continuous patching
